##
# Defines site data and metadata
#
# Author: Matt Turner <matt@mat.phd>
# Date: 15 June 2026
#


website:

  title: "<b>Get Piedmont</b> Insurance"

  navbar:
    background: "#3498db"
    foreground: "#005"
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "More About Jill"

  favicon: favicon.png

  search: false

  open-graph:
    image: images/jill.jpg
  twitter-card:
    image: images/jill.jpg
    card-style: summary_large_image

format:

  html:

    search: false
    theme:
      - cosmo
      - brand
      - styles.scss

    # css: styles.scss
    toc: false


project:
  type: website
