##
# Defines site data and metadata
#
# Author: Matt Turner <matt@mat.phd>
# Date: 15 June 2026
#


website:

  title: "<b>Get Piedmont</b> Insurance"

  navbar:
    background: "#3498db"
    foreground: "#005"
    left:
      - href: about.qmd
        text: "More About Jill"

  search: false

format:

  html:

    search: false
    theme:
      - cosmo
      - brand
      - styles.scss

    # css: styles.scss
    toc: false


project:
  type: website
